[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && REACT_APP_API_URL='' npm run build"
]

[start]
cmd = "python backend/app.py"
